### ISSUE TITLE
Why prerelease? 

### ISSUE THREAD

**Issue by WojciechNagorski** [AigioL/7-Zip.NativeAssets#1]
Is it possible to release the final version?

**Comment by AigioL** [comment]
I am not sure if other non Windows platform packages are stable, and the preview version of the package can also be referenced normally. Just check the radio box to display the preview version

**Comment by AigioL** [comment]
Afterwards, the preview version number will be deleted for packages on Windows platforms, while other platforms will retain the preview version due to uncertainty

**Comment by AigioL** [comment]
Published final version
https://www.nuget.org/packages/7-Zip.NativeAssets.Win32/22.1.0
https://www.nuget.org/packages/7-Zip.NativeAssets.Linux/22.1.0
https://www.nuget.org/packages/7-Zip.NativeAssets.macOS/21.7.0
